package com.jakcray.springbootshiro.mybatisutils.mapper;

import com.jakcray.springbootshiro.mybatisutils.dao.ManageInfoDAO;
import com.jakcray.springbootshiro.mybatisutils.dao.ManageInfoDAOExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface ManageInfoDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manageinfo
     *
     * @mbggenerated
     */
    int countByExample(ManageInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manageinfo
     *
     * @mbggenerated
     */
    int deleteByExample(ManageInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manageinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String idmanageinfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manageinfo
     *
     * @mbggenerated
     */
    int insert(ManageInfoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manageinfo
     *
     * @mbggenerated
     */
    int insertSelective(ManageInfoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manageinfo
     *
     * @mbggenerated
     */
    List<ManageInfoDAO> selectByExample(ManageInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manageinfo
     *
     * @mbggenerated
     */
    ManageInfoDAO selectByPrimaryKey(String idmanageinfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manageinfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ManageInfoDAO record, @Param("example") ManageInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manageinfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ManageInfoDAO record, @Param("example") ManageInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manageinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManageInfoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manageinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManageInfoDAO record);
}