package com.jakcray.springbootshiro.mybatisutils.mapper;

import com.jakcray.springbootshiro.mybatisutils.dao.ModuleDAO;
import com.jakcray.springbootshiro.mybatisutils.dao.ModuleDAOExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface ModuleDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated
     */
    int countByExample(ModuleDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated
     */
    int deleteByExample(ModuleDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String idmodule);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated
     */
    int insert(ModuleDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated
     */
    int insertSelective(ModuleDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated
     */
    List<ModuleDAO> selectByExample(ModuleDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated
     */
    ModuleDAO selectByPrimaryKey(String idmodule);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ModuleDAO record, @Param("example") ModuleDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ModuleDAO record, @Param("example") ModuleDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ModuleDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ModuleDAO record);
}