package com.jakcray.springbootshiro.mybatisutils.mapper;

import com.jakcray.springbootshiro.mybatisutils.dao.UserExtraInfoDAO;
import com.jakcray.springbootshiro.mybatisutils.dao.UserExtraInfoDAOExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface UserExtraInfoDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    int countByExample(UserExtraInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    int deleteByExample(UserExtraInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String iduserextrainfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    int insert(UserExtraInfoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    int insertSelective(UserExtraInfoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    List<UserExtraInfoDAO> selectByExample(UserExtraInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    UserExtraInfoDAO selectByPrimaryKey(String iduserextrainfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserExtraInfoDAO record, @Param("example") UserExtraInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserExtraInfoDAO record, @Param("example") UserExtraInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserExtraInfoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserExtraInfoDAO record);
}