package com.jakcray.springbootshiro.mybatisutils.dao;

import java.util.Date;

public class ManageTypeDAO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column managetype.idmanagetype
     *
     * @mbggenerated
     */
    private String idmanagetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column managetype.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column managetype.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column managetype.logourl
     *
     * @mbggenerated
     */
    private String logourl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column managetype.ts
     *
     * @mbggenerated
     */
    private Date ts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column managetype.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column managetype.idmanagetype
     *
     * @return the value of managetype.idmanagetype
     *
     * @mbggenerated
     */
    public String getIdmanagetype() {
        return idmanagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column managetype.idmanagetype
     *
     * @param idmanagetype the value for managetype.idmanagetype
     *
     * @mbggenerated
     */
    public void setIdmanagetype(String idmanagetype) {
        this.idmanagetype = idmanagetype == null ? null : idmanagetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column managetype.name
     *
     * @return the value of managetype.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column managetype.name
     *
     * @param name the value for managetype.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column managetype.description
     *
     * @return the value of managetype.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column managetype.description
     *
     * @param description the value for managetype.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column managetype.logourl
     *
     * @return the value of managetype.logourl
     *
     * @mbggenerated
     */
    public String getLogourl() {
        return logourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column managetype.logourl
     *
     * @param logourl the value for managetype.logourl
     *
     * @mbggenerated
     */
    public void setLogourl(String logourl) {
        this.logourl = logourl == null ? null : logourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column managetype.ts
     *
     * @return the value of managetype.ts
     *
     * @mbggenerated
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column managetype.ts
     *
     * @param ts the value for managetype.ts
     *
     * @mbggenerated
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column managetype.addtime
     *
     * @return the value of managetype.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column managetype.addtime
     *
     * @param addtime the value for managetype.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}