package com.jakcray.springbootshiro.mybatisutils.dao;

import java.util.Date;

public class ManageRoleDAO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_role.idmanage_role
     *
     * @mbggenerated
     */
    private String idmanageRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_role.idmanage
     *
     * @mbggenerated
     */
    private String idmanage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_role.idrole
     *
     * @mbggenerated
     */
    private String idrole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_role.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_role.ts
     *
     * @mbggenerated
     */
    private Date ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_role.idmanage_role
     *
     * @return the value of manage_role.idmanage_role
     *
     * @mbggenerated
     */
    public String getIdmanageRole() {
        return idmanageRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_role.idmanage_role
     *
     * @param idmanageRole the value for manage_role.idmanage_role
     *
     * @mbggenerated
     */
    public void setIdmanageRole(String idmanageRole) {
        this.idmanageRole = idmanageRole == null ? null : idmanageRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_role.idmanage
     *
     * @return the value of manage_role.idmanage
     *
     * @mbggenerated
     */
    public String getIdmanage() {
        return idmanage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_role.idmanage
     *
     * @param idmanage the value for manage_role.idmanage
     *
     * @mbggenerated
     */
    public void setIdmanage(String idmanage) {
        this.idmanage = idmanage == null ? null : idmanage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_role.idrole
     *
     * @return the value of manage_role.idrole
     *
     * @mbggenerated
     */
    public String getIdrole() {
        return idrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_role.idrole
     *
     * @param idrole the value for manage_role.idrole
     *
     * @mbggenerated
     */
    public void setIdrole(String idrole) {
        this.idrole = idrole == null ? null : idrole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_role.addtime
     *
     * @return the value of manage_role.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_role.addtime
     *
     * @param addtime the value for manage_role.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_role.ts
     *
     * @return the value of manage_role.ts
     *
     * @mbggenerated
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_role.ts
     *
     * @param ts the value for manage_role.ts
     *
     * @mbggenerated
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }
}