package com.jakcray.springbootshiro.mybatisutils.dao;

import java.util.Date;

public class ManageDAO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage.idmanage
     *
     * @mbggenerated
     */
    private String idmanage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage.idmanageinfo
     *
     * @mbggenerated
     */
    private String idmanageinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage.idmanagetype
     *
     * @mbggenerated
     */
    private String idmanagetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage.ts
     *
     * @mbggenerated
     */
    private Date ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage.idmanage
     *
     * @return the value of manage.idmanage
     *
     * @mbggenerated
     */
    public String getIdmanage() {
        return idmanage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage.idmanage
     *
     * @param idmanage the value for manage.idmanage
     *
     * @mbggenerated
     */
    public void setIdmanage(String idmanage) {
        this.idmanage = idmanage == null ? null : idmanage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage.username
     *
     * @return the value of manage.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage.username
     *
     * @param username the value for manage.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage.password
     *
     * @return the value of manage.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage.password
     *
     * @param password the value for manage.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage.status
     *
     * @return the value of manage.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage.status
     *
     * @param status the value for manage.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage.idmanageinfo
     *
     * @return the value of manage.idmanageinfo
     *
     * @mbggenerated
     */
    public String getIdmanageinfo() {
        return idmanageinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage.idmanageinfo
     *
     * @param idmanageinfo the value for manage.idmanageinfo
     *
     * @mbggenerated
     */
    public void setIdmanageinfo(String idmanageinfo) {
        this.idmanageinfo = idmanageinfo == null ? null : idmanageinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage.idmanagetype
     *
     * @return the value of manage.idmanagetype
     *
     * @mbggenerated
     */
    public String getIdmanagetype() {
        return idmanagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage.idmanagetype
     *
     * @param idmanagetype the value for manage.idmanagetype
     *
     * @mbggenerated
     */
    public void setIdmanagetype(String idmanagetype) {
        this.idmanagetype = idmanagetype == null ? null : idmanagetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage.addtime
     *
     * @return the value of manage.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage.addtime
     *
     * @param addtime the value for manage.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage.ts
     *
     * @return the value of manage.ts
     *
     * @mbggenerated
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage.ts
     *
     * @param ts the value for manage.ts
     *
     * @mbggenerated
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }
}