package com.jakcray.springbootshiro.mybatisutils.dao;

import java.util.Date;

public class ManageInfoDAO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manageinfo.idmanageinfo
     *
     * @mbggenerated
     */
    private String idmanageinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manageinfo.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manageinfo.upper
     *
     * @mbggenerated
     */
    private String upper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manageinfo.idmanagetype
     *
     * @mbggenerated
     */
    private String idmanagetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manageinfo.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manageinfo.ts
     *
     * @mbggenerated
     */
    private Date ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manageinfo.idmanageinfo
     *
     * @return the value of manageinfo.idmanageinfo
     *
     * @mbggenerated
     */
    public String getIdmanageinfo() {
        return idmanageinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manageinfo.idmanageinfo
     *
     * @param idmanageinfo the value for manageinfo.idmanageinfo
     *
     * @mbggenerated
     */
    public void setIdmanageinfo(String idmanageinfo) {
        this.idmanageinfo = idmanageinfo == null ? null : idmanageinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manageinfo.name
     *
     * @return the value of manageinfo.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manageinfo.name
     *
     * @param name the value for manageinfo.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manageinfo.upper
     *
     * @return the value of manageinfo.upper
     *
     * @mbggenerated
     */
    public String getUpper() {
        return upper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manageinfo.upper
     *
     * @param upper the value for manageinfo.upper
     *
     * @mbggenerated
     */
    public void setUpper(String upper) {
        this.upper = upper == null ? null : upper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manageinfo.idmanagetype
     *
     * @return the value of manageinfo.idmanagetype
     *
     * @mbggenerated
     */
    public String getIdmanagetype() {
        return idmanagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manageinfo.idmanagetype
     *
     * @param idmanagetype the value for manageinfo.idmanagetype
     *
     * @mbggenerated
     */
    public void setIdmanagetype(String idmanagetype) {
        this.idmanagetype = idmanagetype == null ? null : idmanagetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manageinfo.addtime
     *
     * @return the value of manageinfo.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manageinfo.addtime
     *
     * @param addtime the value for manageinfo.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manageinfo.ts
     *
     * @return the value of manageinfo.ts
     *
     * @mbggenerated
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manageinfo.ts
     *
     * @param ts the value for manageinfo.ts
     *
     * @mbggenerated
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }
}