package com.jakcray.springbootshiro.mybatisutils.dao;

import java.util.Date;

public class ModuleDAO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.idmodule
     *
     * @mbggenerated
     */
    private String idmodule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.mname
     *
     * @mbggenerated
     */
    private String mname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.ts
     *
     * @mbggenerated
     */
    private Date ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.idmodule
     *
     * @return the value of module.idmodule
     *
     * @mbggenerated
     */
    public String getIdmodule() {
        return idmodule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.idmodule
     *
     * @param idmodule the value for module.idmodule
     *
     * @mbggenerated
     */
    public void setIdmodule(String idmodule) {
        this.idmodule = idmodule == null ? null : idmodule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.mname
     *
     * @return the value of module.mname
     *
     * @mbggenerated
     */
    public String getMname() {
        return mname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.mname
     *
     * @param mname the value for module.mname
     *
     * @mbggenerated
     */
    public void setMname(String mname) {
        this.mname = mname == null ? null : mname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.addtime
     *
     * @return the value of module.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.addtime
     *
     * @param addtime the value for module.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.ts
     *
     * @return the value of module.ts
     *
     * @mbggenerated
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.ts
     *
     * @param ts the value for module.ts
     *
     * @mbggenerated
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }
}