package com.jakcray.springbootshiro.mybatisutils.dao;

import java.util.Date;

public class RolePermissionDAO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.idrole_permission
     *
     * @mbggenerated
     */
    private String idrolePermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.idrole
     *
     * @mbggenerated
     */
    private String idrole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.idpermission
     *
     * @mbggenerated
     */
    private String idpermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.ts
     *
     * @mbggenerated
     */
    private Date ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.idrole_permission
     *
     * @return the value of role_permission.idrole_permission
     *
     * @mbggenerated
     */
    public String getIdrolePermission() {
        return idrolePermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.idrole_permission
     *
     * @param idrolePermission the value for role_permission.idrole_permission
     *
     * @mbggenerated
     */
    public void setIdrolePermission(String idrolePermission) {
        this.idrolePermission = idrolePermission == null ? null : idrolePermission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.idrole
     *
     * @return the value of role_permission.idrole
     *
     * @mbggenerated
     */
    public String getIdrole() {
        return idrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.idrole
     *
     * @param idrole the value for role_permission.idrole
     *
     * @mbggenerated
     */
    public void setIdrole(String idrole) {
        this.idrole = idrole == null ? null : idrole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.idpermission
     *
     * @return the value of role_permission.idpermission
     *
     * @mbggenerated
     */
    public String getIdpermission() {
        return idpermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.idpermission
     *
     * @param idpermission the value for role_permission.idpermission
     *
     * @mbggenerated
     */
    public void setIdpermission(String idpermission) {
        this.idpermission = idpermission == null ? null : idpermission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.addtime
     *
     * @return the value of role_permission.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.addtime
     *
     * @param addtime the value for role_permission.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.ts
     *
     * @return the value of role_permission.ts
     *
     * @mbggenerated
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.ts
     *
     * @param ts the value for role_permission.ts
     *
     * @mbggenerated
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }
}