package com.jakcray.springbootshiro.mybatisutils.dao;

import java.util.Date;

public class UserExtraInfoDAO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.iduserextrainfo
     *
     * @mbggenerated
     */
    private String iduserextrainfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.porturl
     *
     * @mbggenerated
     */
    private String porturl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.portname
     *
     * @mbggenerated
     */
    private String portname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.portno
     *
     * @mbggenerated
     */
    private String portno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.port_ts
     *
     * @mbggenerated
     */
    private Date portTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.housestatus
     *
     * @mbggenerated
     */
    private String housestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.houseaddress
     *
     * @mbggenerated
     */
    private String houseaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.houseinfo
     *
     * @mbggenerated
     */
    private String houseinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.houseurl
     *
     * @mbggenerated
     */
    private String houseurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.house_ts
     *
     * @mbggenerated
     */
    private Date houseTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.carstatus
     *
     * @mbggenerated
     */
    private String carstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.cartype
     *
     * @mbggenerated
     */
    private String cartype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.carinfo
     *
     * @mbggenerated
     */
    private String carinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.carurl
     *
     * @mbggenerated
     */
    private String carurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.car_ts
     *
     * @mbggenerated
     */
    private Date carTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.degreestatus
     *
     * @mbggenerated
     */
    private String degreestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.degreelevel
     *
     * @mbggenerated
     */
    private String degreelevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.degreeurl
     *
     * @mbggenerated
     */
    private String degreeurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.degree_ts
     *
     * @mbggenerated
     */
    private String degreeTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.headurl
     *
     * @mbggenerated
     */
    private String headurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.head_ts
     *
     * @mbggenerated
     */
    private Date headTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.iduser
     *
     * @mbggenerated
     */
    private String iduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.iduserinfo
     *
     * @mbggenerated
     */
    private String iduserinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userextrainfo.ts
     *
     * @mbggenerated
     */
    private Date ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.iduserextrainfo
     *
     * @return the value of userextrainfo.iduserextrainfo
     *
     * @mbggenerated
     */
    public String getIduserextrainfo() {
        return iduserextrainfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.iduserextrainfo
     *
     * @param iduserextrainfo the value for userextrainfo.iduserextrainfo
     *
     * @mbggenerated
     */
    public void setIduserextrainfo(String iduserextrainfo) {
        this.iduserextrainfo = iduserextrainfo == null ? null : iduserextrainfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.porturl
     *
     * @return the value of userextrainfo.porturl
     *
     * @mbggenerated
     */
    public String getPorturl() {
        return porturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.porturl
     *
     * @param porturl the value for userextrainfo.porturl
     *
     * @mbggenerated
     */
    public void setPorturl(String porturl) {
        this.porturl = porturl == null ? null : porturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.portname
     *
     * @return the value of userextrainfo.portname
     *
     * @mbggenerated
     */
    public String getPortname() {
        return portname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.portname
     *
     * @param portname the value for userextrainfo.portname
     *
     * @mbggenerated
     */
    public void setPortname(String portname) {
        this.portname = portname == null ? null : portname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.portno
     *
     * @return the value of userextrainfo.portno
     *
     * @mbggenerated
     */
    public String getPortno() {
        return portno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.portno
     *
     * @param portno the value for userextrainfo.portno
     *
     * @mbggenerated
     */
    public void setPortno(String portno) {
        this.portno = portno == null ? null : portno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.port_ts
     *
     * @return the value of userextrainfo.port_ts
     *
     * @mbggenerated
     */
    public Date getPortTs() {
        return portTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.port_ts
     *
     * @param portTs the value for userextrainfo.port_ts
     *
     * @mbggenerated
     */
    public void setPortTs(Date portTs) {
        this.portTs = portTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.housestatus
     *
     * @return the value of userextrainfo.housestatus
     *
     * @mbggenerated
     */
    public String getHousestatus() {
        return housestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.housestatus
     *
     * @param housestatus the value for userextrainfo.housestatus
     *
     * @mbggenerated
     */
    public void setHousestatus(String housestatus) {
        this.housestatus = housestatus == null ? null : housestatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.houseaddress
     *
     * @return the value of userextrainfo.houseaddress
     *
     * @mbggenerated
     */
    public String getHouseaddress() {
        return houseaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.houseaddress
     *
     * @param houseaddress the value for userextrainfo.houseaddress
     *
     * @mbggenerated
     */
    public void setHouseaddress(String houseaddress) {
        this.houseaddress = houseaddress == null ? null : houseaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.houseinfo
     *
     * @return the value of userextrainfo.houseinfo
     *
     * @mbggenerated
     */
    public String getHouseinfo() {
        return houseinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.houseinfo
     *
     * @param houseinfo the value for userextrainfo.houseinfo
     *
     * @mbggenerated
     */
    public void setHouseinfo(String houseinfo) {
        this.houseinfo = houseinfo == null ? null : houseinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.houseurl
     *
     * @return the value of userextrainfo.houseurl
     *
     * @mbggenerated
     */
    public String getHouseurl() {
        return houseurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.houseurl
     *
     * @param houseurl the value for userextrainfo.houseurl
     *
     * @mbggenerated
     */
    public void setHouseurl(String houseurl) {
        this.houseurl = houseurl == null ? null : houseurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.house_ts
     *
     * @return the value of userextrainfo.house_ts
     *
     * @mbggenerated
     */
    public Date getHouseTs() {
        return houseTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.house_ts
     *
     * @param houseTs the value for userextrainfo.house_ts
     *
     * @mbggenerated
     */
    public void setHouseTs(Date houseTs) {
        this.houseTs = houseTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.carstatus
     *
     * @return the value of userextrainfo.carstatus
     *
     * @mbggenerated
     */
    public String getCarstatus() {
        return carstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.carstatus
     *
     * @param carstatus the value for userextrainfo.carstatus
     *
     * @mbggenerated
     */
    public void setCarstatus(String carstatus) {
        this.carstatus = carstatus == null ? null : carstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.cartype
     *
     * @return the value of userextrainfo.cartype
     *
     * @mbggenerated
     */
    public String getCartype() {
        return cartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.cartype
     *
     * @param cartype the value for userextrainfo.cartype
     *
     * @mbggenerated
     */
    public void setCartype(String cartype) {
        this.cartype = cartype == null ? null : cartype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.carinfo
     *
     * @return the value of userextrainfo.carinfo
     *
     * @mbggenerated
     */
    public String getCarinfo() {
        return carinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.carinfo
     *
     * @param carinfo the value for userextrainfo.carinfo
     *
     * @mbggenerated
     */
    public void setCarinfo(String carinfo) {
        this.carinfo = carinfo == null ? null : carinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.carurl
     *
     * @return the value of userextrainfo.carurl
     *
     * @mbggenerated
     */
    public String getCarurl() {
        return carurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.carurl
     *
     * @param carurl the value for userextrainfo.carurl
     *
     * @mbggenerated
     */
    public void setCarurl(String carurl) {
        this.carurl = carurl == null ? null : carurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.car_ts
     *
     * @return the value of userextrainfo.car_ts
     *
     * @mbggenerated
     */
    public Date getCarTs() {
        return carTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.car_ts
     *
     * @param carTs the value for userextrainfo.car_ts
     *
     * @mbggenerated
     */
    public void setCarTs(Date carTs) {
        this.carTs = carTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.degreestatus
     *
     * @return the value of userextrainfo.degreestatus
     *
     * @mbggenerated
     */
    public String getDegreestatus() {
        return degreestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.degreestatus
     *
     * @param degreestatus the value for userextrainfo.degreestatus
     *
     * @mbggenerated
     */
    public void setDegreestatus(String degreestatus) {
        this.degreestatus = degreestatus == null ? null : degreestatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.degreelevel
     *
     * @return the value of userextrainfo.degreelevel
     *
     * @mbggenerated
     */
    public String getDegreelevel() {
        return degreelevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.degreelevel
     *
     * @param degreelevel the value for userextrainfo.degreelevel
     *
     * @mbggenerated
     */
    public void setDegreelevel(String degreelevel) {
        this.degreelevel = degreelevel == null ? null : degreelevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.degreeurl
     *
     * @return the value of userextrainfo.degreeurl
     *
     * @mbggenerated
     */
    public String getDegreeurl() {
        return degreeurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.degreeurl
     *
     * @param degreeurl the value for userextrainfo.degreeurl
     *
     * @mbggenerated
     */
    public void setDegreeurl(String degreeurl) {
        this.degreeurl = degreeurl == null ? null : degreeurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.degree_ts
     *
     * @return the value of userextrainfo.degree_ts
     *
     * @mbggenerated
     */
    public String getDegreeTs() {
        return degreeTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.degree_ts
     *
     * @param degreeTs the value for userextrainfo.degree_ts
     *
     * @mbggenerated
     */
    public void setDegreeTs(String degreeTs) {
        this.degreeTs = degreeTs == null ? null : degreeTs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.headurl
     *
     * @return the value of userextrainfo.headurl
     *
     * @mbggenerated
     */
    public String getHeadurl() {
        return headurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.headurl
     *
     * @param headurl the value for userextrainfo.headurl
     *
     * @mbggenerated
     */
    public void setHeadurl(String headurl) {
        this.headurl = headurl == null ? null : headurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.head_ts
     *
     * @return the value of userextrainfo.head_ts
     *
     * @mbggenerated
     */
    public Date getHeadTs() {
        return headTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.head_ts
     *
     * @param headTs the value for userextrainfo.head_ts
     *
     * @mbggenerated
     */
    public void setHeadTs(Date headTs) {
        this.headTs = headTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.iduser
     *
     * @return the value of userextrainfo.iduser
     *
     * @mbggenerated
     */
    public String getIduser() {
        return iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.iduser
     *
     * @param iduser the value for userextrainfo.iduser
     *
     * @mbggenerated
     */
    public void setIduser(String iduser) {
        this.iduser = iduser == null ? null : iduser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.iduserinfo
     *
     * @return the value of userextrainfo.iduserinfo
     *
     * @mbggenerated
     */
    public String getIduserinfo() {
        return iduserinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.iduserinfo
     *
     * @param iduserinfo the value for userextrainfo.iduserinfo
     *
     * @mbggenerated
     */
    public void setIduserinfo(String iduserinfo) {
        this.iduserinfo = iduserinfo == null ? null : iduserinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.addtime
     *
     * @return the value of userextrainfo.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.addtime
     *
     * @param addtime the value for userextrainfo.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userextrainfo.ts
     *
     * @return the value of userextrainfo.ts
     *
     * @mbggenerated
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userextrainfo.ts
     *
     * @param ts the value for userextrainfo.ts
     *
     * @mbggenerated
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }
}