package com.jakcray.springbootshiro.mybatisutils.dao;

import java.util.Date;

public class UserDAO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.iduser
     *
     * @mbggenerated
     */
    private String iduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wechat
     *
     * @mbggenerated
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phoneno
     *
     * @mbggenerated
     */
    private String phoneno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.iduserinfo
     *
     * @mbggenerated
     */
    private String iduserinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.iduserextrainfo
     *
     * @mbggenerated
     */
    private String iduserextrainfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ts
     *
     * @mbggenerated
     */
    private Date ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.iduser
     *
     * @return the value of user.iduser
     *
     * @mbggenerated
     */
    public String getIduser() {
        return iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.iduser
     *
     * @param iduser the value for user.iduser
     *
     * @mbggenerated
     */
    public void setIduser(String iduser) {
        this.iduser = iduser == null ? null : iduser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wechat
     *
     * @return the value of user.wechat
     *
     * @mbggenerated
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wechat
     *
     * @param wechat the value for user.wechat
     *
     * @mbggenerated
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phoneno
     *
     * @return the value of user.phoneno
     *
     * @mbggenerated
     */
    public String getPhoneno() {
        return phoneno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phoneno
     *
     * @param phoneno the value for user.phoneno
     *
     * @mbggenerated
     */
    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno == null ? null : phoneno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.status
     *
     * @return the value of user.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.status
     *
     * @param status the value for user.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.iduserinfo
     *
     * @return the value of user.iduserinfo
     *
     * @mbggenerated
     */
    public String getIduserinfo() {
        return iduserinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.iduserinfo
     *
     * @param iduserinfo the value for user.iduserinfo
     *
     * @mbggenerated
     */
    public void setIduserinfo(String iduserinfo) {
        this.iduserinfo = iduserinfo == null ? null : iduserinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.iduserextrainfo
     *
     * @return the value of user.iduserextrainfo
     *
     * @mbggenerated
     */
    public String getIduserextrainfo() {
        return iduserextrainfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.iduserextrainfo
     *
     * @param iduserextrainfo the value for user.iduserextrainfo
     *
     * @mbggenerated
     */
    public void setIduserextrainfo(String iduserextrainfo) {
        this.iduserextrainfo = iduserextrainfo == null ? null : iduserextrainfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.addtime
     *
     * @return the value of user.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.addtime
     *
     * @param addtime the value for user.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ts
     *
     * @return the value of user.ts
     *
     * @mbggenerated
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ts
     *
     * @param ts the value for user.ts
     *
     * @mbggenerated
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }
}