package com.jakcray.springbootshiro.mybatisutils.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExtraInfoDAOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    public UserExtraInfoDAOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIduserextrainfoIsNull() {
            addCriterion("iduserextrainfo is null");
            return (Criteria) this;
        }

        public Criteria andIduserextrainfoIsNotNull() {
            addCriterion("iduserextrainfo is not null");
            return (Criteria) this;
        }

        public Criteria andIduserextrainfoEqualTo(String value) {
            addCriterion("iduserextrainfo =", value, "iduserextrainfo");
            return (Criteria) this;
        }

        public Criteria andIduserextrainfoNotEqualTo(String value) {
            addCriterion("iduserextrainfo <>", value, "iduserextrainfo");
            return (Criteria) this;
        }

        public Criteria andIduserextrainfoGreaterThan(String value) {
            addCriterion("iduserextrainfo >", value, "iduserextrainfo");
            return (Criteria) this;
        }

        public Criteria andIduserextrainfoGreaterThanOrEqualTo(String value) {
            addCriterion("iduserextrainfo >=", value, "iduserextrainfo");
            return (Criteria) this;
        }

        public Criteria andIduserextrainfoLessThan(String value) {
            addCriterion("iduserextrainfo <", value, "iduserextrainfo");
            return (Criteria) this;
        }

        public Criteria andIduserextrainfoLessThanOrEqualTo(String value) {
            addCriterion("iduserextrainfo <=", value, "iduserextrainfo");
            return (Criteria) this;
        }

        public Criteria andIduserextrainfoLike(String value) {
            addCriterion("iduserextrainfo like", value, "iduserextrainfo");
            return (Criteria) this;
        }

        public Criteria andIduserextrainfoNotLike(String value) {
            addCriterion("iduserextrainfo not like", value, "iduserextrainfo");
            return (Criteria) this;
        }

        public Criteria andIduserextrainfoIn(List<String> values) {
            addCriterion("iduserextrainfo in", values, "iduserextrainfo");
            return (Criteria) this;
        }

        public Criteria andIduserextrainfoNotIn(List<String> values) {
            addCriterion("iduserextrainfo not in", values, "iduserextrainfo");
            return (Criteria) this;
        }

        public Criteria andIduserextrainfoBetween(String value1, String value2) {
            addCriterion("iduserextrainfo between", value1, value2, "iduserextrainfo");
            return (Criteria) this;
        }

        public Criteria andIduserextrainfoNotBetween(String value1, String value2) {
            addCriterion("iduserextrainfo not between", value1, value2, "iduserextrainfo");
            return (Criteria) this;
        }

        public Criteria andPorturlIsNull() {
            addCriterion("porturl is null");
            return (Criteria) this;
        }

        public Criteria andPorturlIsNotNull() {
            addCriterion("porturl is not null");
            return (Criteria) this;
        }

        public Criteria andPorturlEqualTo(String value) {
            addCriterion("porturl =", value, "porturl");
            return (Criteria) this;
        }

        public Criteria andPorturlNotEqualTo(String value) {
            addCriterion("porturl <>", value, "porturl");
            return (Criteria) this;
        }

        public Criteria andPorturlGreaterThan(String value) {
            addCriterion("porturl >", value, "porturl");
            return (Criteria) this;
        }

        public Criteria andPorturlGreaterThanOrEqualTo(String value) {
            addCriterion("porturl >=", value, "porturl");
            return (Criteria) this;
        }

        public Criteria andPorturlLessThan(String value) {
            addCriterion("porturl <", value, "porturl");
            return (Criteria) this;
        }

        public Criteria andPorturlLessThanOrEqualTo(String value) {
            addCriterion("porturl <=", value, "porturl");
            return (Criteria) this;
        }

        public Criteria andPorturlLike(String value) {
            addCriterion("porturl like", value, "porturl");
            return (Criteria) this;
        }

        public Criteria andPorturlNotLike(String value) {
            addCriterion("porturl not like", value, "porturl");
            return (Criteria) this;
        }

        public Criteria andPorturlIn(List<String> values) {
            addCriterion("porturl in", values, "porturl");
            return (Criteria) this;
        }

        public Criteria andPorturlNotIn(List<String> values) {
            addCriterion("porturl not in", values, "porturl");
            return (Criteria) this;
        }

        public Criteria andPorturlBetween(String value1, String value2) {
            addCriterion("porturl between", value1, value2, "porturl");
            return (Criteria) this;
        }

        public Criteria andPorturlNotBetween(String value1, String value2) {
            addCriterion("porturl not between", value1, value2, "porturl");
            return (Criteria) this;
        }

        public Criteria andPortnameIsNull() {
            addCriterion("portname is null");
            return (Criteria) this;
        }

        public Criteria andPortnameIsNotNull() {
            addCriterion("portname is not null");
            return (Criteria) this;
        }

        public Criteria andPortnameEqualTo(String value) {
            addCriterion("portname =", value, "portname");
            return (Criteria) this;
        }

        public Criteria andPortnameNotEqualTo(String value) {
            addCriterion("portname <>", value, "portname");
            return (Criteria) this;
        }

        public Criteria andPortnameGreaterThan(String value) {
            addCriterion("portname >", value, "portname");
            return (Criteria) this;
        }

        public Criteria andPortnameGreaterThanOrEqualTo(String value) {
            addCriterion("portname >=", value, "portname");
            return (Criteria) this;
        }

        public Criteria andPortnameLessThan(String value) {
            addCriterion("portname <", value, "portname");
            return (Criteria) this;
        }

        public Criteria andPortnameLessThanOrEqualTo(String value) {
            addCriterion("portname <=", value, "portname");
            return (Criteria) this;
        }

        public Criteria andPortnameLike(String value) {
            addCriterion("portname like", value, "portname");
            return (Criteria) this;
        }

        public Criteria andPortnameNotLike(String value) {
            addCriterion("portname not like", value, "portname");
            return (Criteria) this;
        }

        public Criteria andPortnameIn(List<String> values) {
            addCriterion("portname in", values, "portname");
            return (Criteria) this;
        }

        public Criteria andPortnameNotIn(List<String> values) {
            addCriterion("portname not in", values, "portname");
            return (Criteria) this;
        }

        public Criteria andPortnameBetween(String value1, String value2) {
            addCriterion("portname between", value1, value2, "portname");
            return (Criteria) this;
        }

        public Criteria andPortnameNotBetween(String value1, String value2) {
            addCriterion("portname not between", value1, value2, "portname");
            return (Criteria) this;
        }

        public Criteria andPortnoIsNull() {
            addCriterion("portno is null");
            return (Criteria) this;
        }

        public Criteria andPortnoIsNotNull() {
            addCriterion("portno is not null");
            return (Criteria) this;
        }

        public Criteria andPortnoEqualTo(String value) {
            addCriterion("portno =", value, "portno");
            return (Criteria) this;
        }

        public Criteria andPortnoNotEqualTo(String value) {
            addCriterion("portno <>", value, "portno");
            return (Criteria) this;
        }

        public Criteria andPortnoGreaterThan(String value) {
            addCriterion("portno >", value, "portno");
            return (Criteria) this;
        }

        public Criteria andPortnoGreaterThanOrEqualTo(String value) {
            addCriterion("portno >=", value, "portno");
            return (Criteria) this;
        }

        public Criteria andPortnoLessThan(String value) {
            addCriterion("portno <", value, "portno");
            return (Criteria) this;
        }

        public Criteria andPortnoLessThanOrEqualTo(String value) {
            addCriterion("portno <=", value, "portno");
            return (Criteria) this;
        }

        public Criteria andPortnoLike(String value) {
            addCriterion("portno like", value, "portno");
            return (Criteria) this;
        }

        public Criteria andPortnoNotLike(String value) {
            addCriterion("portno not like", value, "portno");
            return (Criteria) this;
        }

        public Criteria andPortnoIn(List<String> values) {
            addCriterion("portno in", values, "portno");
            return (Criteria) this;
        }

        public Criteria andPortnoNotIn(List<String> values) {
            addCriterion("portno not in", values, "portno");
            return (Criteria) this;
        }

        public Criteria andPortnoBetween(String value1, String value2) {
            addCriterion("portno between", value1, value2, "portno");
            return (Criteria) this;
        }

        public Criteria andPortnoNotBetween(String value1, String value2) {
            addCriterion("portno not between", value1, value2, "portno");
            return (Criteria) this;
        }

        public Criteria andPortTsIsNull() {
            addCriterion("port_ts is null");
            return (Criteria) this;
        }

        public Criteria andPortTsIsNotNull() {
            addCriterion("port_ts is not null");
            return (Criteria) this;
        }

        public Criteria andPortTsEqualTo(Date value) {
            addCriterion("port_ts =", value, "portTs");
            return (Criteria) this;
        }

        public Criteria andPortTsNotEqualTo(Date value) {
            addCriterion("port_ts <>", value, "portTs");
            return (Criteria) this;
        }

        public Criteria andPortTsGreaterThan(Date value) {
            addCriterion("port_ts >", value, "portTs");
            return (Criteria) this;
        }

        public Criteria andPortTsGreaterThanOrEqualTo(Date value) {
            addCriterion("port_ts >=", value, "portTs");
            return (Criteria) this;
        }

        public Criteria andPortTsLessThan(Date value) {
            addCriterion("port_ts <", value, "portTs");
            return (Criteria) this;
        }

        public Criteria andPortTsLessThanOrEqualTo(Date value) {
            addCriterion("port_ts <=", value, "portTs");
            return (Criteria) this;
        }

        public Criteria andPortTsIn(List<Date> values) {
            addCriterion("port_ts in", values, "portTs");
            return (Criteria) this;
        }

        public Criteria andPortTsNotIn(List<Date> values) {
            addCriterion("port_ts not in", values, "portTs");
            return (Criteria) this;
        }

        public Criteria andPortTsBetween(Date value1, Date value2) {
            addCriterion("port_ts between", value1, value2, "portTs");
            return (Criteria) this;
        }

        public Criteria andPortTsNotBetween(Date value1, Date value2) {
            addCriterion("port_ts not between", value1, value2, "portTs");
            return (Criteria) this;
        }

        public Criteria andHousestatusIsNull() {
            addCriterion("housestatus is null");
            return (Criteria) this;
        }

        public Criteria andHousestatusIsNotNull() {
            addCriterion("housestatus is not null");
            return (Criteria) this;
        }

        public Criteria andHousestatusEqualTo(String value) {
            addCriterion("housestatus =", value, "housestatus");
            return (Criteria) this;
        }

        public Criteria andHousestatusNotEqualTo(String value) {
            addCriterion("housestatus <>", value, "housestatus");
            return (Criteria) this;
        }

        public Criteria andHousestatusGreaterThan(String value) {
            addCriterion("housestatus >", value, "housestatus");
            return (Criteria) this;
        }

        public Criteria andHousestatusGreaterThanOrEqualTo(String value) {
            addCriterion("housestatus >=", value, "housestatus");
            return (Criteria) this;
        }

        public Criteria andHousestatusLessThan(String value) {
            addCriterion("housestatus <", value, "housestatus");
            return (Criteria) this;
        }

        public Criteria andHousestatusLessThanOrEqualTo(String value) {
            addCriterion("housestatus <=", value, "housestatus");
            return (Criteria) this;
        }

        public Criteria andHousestatusLike(String value) {
            addCriterion("housestatus like", value, "housestatus");
            return (Criteria) this;
        }

        public Criteria andHousestatusNotLike(String value) {
            addCriterion("housestatus not like", value, "housestatus");
            return (Criteria) this;
        }

        public Criteria andHousestatusIn(List<String> values) {
            addCriterion("housestatus in", values, "housestatus");
            return (Criteria) this;
        }

        public Criteria andHousestatusNotIn(List<String> values) {
            addCriterion("housestatus not in", values, "housestatus");
            return (Criteria) this;
        }

        public Criteria andHousestatusBetween(String value1, String value2) {
            addCriterion("housestatus between", value1, value2, "housestatus");
            return (Criteria) this;
        }

        public Criteria andHousestatusNotBetween(String value1, String value2) {
            addCriterion("housestatus not between", value1, value2, "housestatus");
            return (Criteria) this;
        }

        public Criteria andHouseaddressIsNull() {
            addCriterion("houseaddress is null");
            return (Criteria) this;
        }

        public Criteria andHouseaddressIsNotNull() {
            addCriterion("houseaddress is not null");
            return (Criteria) this;
        }

        public Criteria andHouseaddressEqualTo(String value) {
            addCriterion("houseaddress =", value, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressNotEqualTo(String value) {
            addCriterion("houseaddress <>", value, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressGreaterThan(String value) {
            addCriterion("houseaddress >", value, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressGreaterThanOrEqualTo(String value) {
            addCriterion("houseaddress >=", value, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressLessThan(String value) {
            addCriterion("houseaddress <", value, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressLessThanOrEqualTo(String value) {
            addCriterion("houseaddress <=", value, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressLike(String value) {
            addCriterion("houseaddress like", value, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressNotLike(String value) {
            addCriterion("houseaddress not like", value, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressIn(List<String> values) {
            addCriterion("houseaddress in", values, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressNotIn(List<String> values) {
            addCriterion("houseaddress not in", values, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressBetween(String value1, String value2) {
            addCriterion("houseaddress between", value1, value2, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseaddressNotBetween(String value1, String value2) {
            addCriterion("houseaddress not between", value1, value2, "houseaddress");
            return (Criteria) this;
        }

        public Criteria andHouseinfoIsNull() {
            addCriterion("houseinfo is null");
            return (Criteria) this;
        }

        public Criteria andHouseinfoIsNotNull() {
            addCriterion("houseinfo is not null");
            return (Criteria) this;
        }

        public Criteria andHouseinfoEqualTo(String value) {
            addCriterion("houseinfo =", value, "houseinfo");
            return (Criteria) this;
        }

        public Criteria andHouseinfoNotEqualTo(String value) {
            addCriterion("houseinfo <>", value, "houseinfo");
            return (Criteria) this;
        }

        public Criteria andHouseinfoGreaterThan(String value) {
            addCriterion("houseinfo >", value, "houseinfo");
            return (Criteria) this;
        }

        public Criteria andHouseinfoGreaterThanOrEqualTo(String value) {
            addCriterion("houseinfo >=", value, "houseinfo");
            return (Criteria) this;
        }

        public Criteria andHouseinfoLessThan(String value) {
            addCriterion("houseinfo <", value, "houseinfo");
            return (Criteria) this;
        }

        public Criteria andHouseinfoLessThanOrEqualTo(String value) {
            addCriterion("houseinfo <=", value, "houseinfo");
            return (Criteria) this;
        }

        public Criteria andHouseinfoLike(String value) {
            addCriterion("houseinfo like", value, "houseinfo");
            return (Criteria) this;
        }

        public Criteria andHouseinfoNotLike(String value) {
            addCriterion("houseinfo not like", value, "houseinfo");
            return (Criteria) this;
        }

        public Criteria andHouseinfoIn(List<String> values) {
            addCriterion("houseinfo in", values, "houseinfo");
            return (Criteria) this;
        }

        public Criteria andHouseinfoNotIn(List<String> values) {
            addCriterion("houseinfo not in", values, "houseinfo");
            return (Criteria) this;
        }

        public Criteria andHouseinfoBetween(String value1, String value2) {
            addCriterion("houseinfo between", value1, value2, "houseinfo");
            return (Criteria) this;
        }

        public Criteria andHouseinfoNotBetween(String value1, String value2) {
            addCriterion("houseinfo not between", value1, value2, "houseinfo");
            return (Criteria) this;
        }

        public Criteria andHouseurlIsNull() {
            addCriterion("houseurl is null");
            return (Criteria) this;
        }

        public Criteria andHouseurlIsNotNull() {
            addCriterion("houseurl is not null");
            return (Criteria) this;
        }

        public Criteria andHouseurlEqualTo(String value) {
            addCriterion("houseurl =", value, "houseurl");
            return (Criteria) this;
        }

        public Criteria andHouseurlNotEqualTo(String value) {
            addCriterion("houseurl <>", value, "houseurl");
            return (Criteria) this;
        }

        public Criteria andHouseurlGreaterThan(String value) {
            addCriterion("houseurl >", value, "houseurl");
            return (Criteria) this;
        }

        public Criteria andHouseurlGreaterThanOrEqualTo(String value) {
            addCriterion("houseurl >=", value, "houseurl");
            return (Criteria) this;
        }

        public Criteria andHouseurlLessThan(String value) {
            addCriterion("houseurl <", value, "houseurl");
            return (Criteria) this;
        }

        public Criteria andHouseurlLessThanOrEqualTo(String value) {
            addCriterion("houseurl <=", value, "houseurl");
            return (Criteria) this;
        }

        public Criteria andHouseurlLike(String value) {
            addCriterion("houseurl like", value, "houseurl");
            return (Criteria) this;
        }

        public Criteria andHouseurlNotLike(String value) {
            addCriterion("houseurl not like", value, "houseurl");
            return (Criteria) this;
        }

        public Criteria andHouseurlIn(List<String> values) {
            addCriterion("houseurl in", values, "houseurl");
            return (Criteria) this;
        }

        public Criteria andHouseurlNotIn(List<String> values) {
            addCriterion("houseurl not in", values, "houseurl");
            return (Criteria) this;
        }

        public Criteria andHouseurlBetween(String value1, String value2) {
            addCriterion("houseurl between", value1, value2, "houseurl");
            return (Criteria) this;
        }

        public Criteria andHouseurlNotBetween(String value1, String value2) {
            addCriterion("houseurl not between", value1, value2, "houseurl");
            return (Criteria) this;
        }

        public Criteria andHouseTsIsNull() {
            addCriterion("house_ts is null");
            return (Criteria) this;
        }

        public Criteria andHouseTsIsNotNull() {
            addCriterion("house_ts is not null");
            return (Criteria) this;
        }

        public Criteria andHouseTsEqualTo(Date value) {
            addCriterion("house_ts =", value, "houseTs");
            return (Criteria) this;
        }

        public Criteria andHouseTsNotEqualTo(Date value) {
            addCriterion("house_ts <>", value, "houseTs");
            return (Criteria) this;
        }

        public Criteria andHouseTsGreaterThan(Date value) {
            addCriterion("house_ts >", value, "houseTs");
            return (Criteria) this;
        }

        public Criteria andHouseTsGreaterThanOrEqualTo(Date value) {
            addCriterion("house_ts >=", value, "houseTs");
            return (Criteria) this;
        }

        public Criteria andHouseTsLessThan(Date value) {
            addCriterion("house_ts <", value, "houseTs");
            return (Criteria) this;
        }

        public Criteria andHouseTsLessThanOrEqualTo(Date value) {
            addCriterion("house_ts <=", value, "houseTs");
            return (Criteria) this;
        }

        public Criteria andHouseTsIn(List<Date> values) {
            addCriterion("house_ts in", values, "houseTs");
            return (Criteria) this;
        }

        public Criteria andHouseTsNotIn(List<Date> values) {
            addCriterion("house_ts not in", values, "houseTs");
            return (Criteria) this;
        }

        public Criteria andHouseTsBetween(Date value1, Date value2) {
            addCriterion("house_ts between", value1, value2, "houseTs");
            return (Criteria) this;
        }

        public Criteria andHouseTsNotBetween(Date value1, Date value2) {
            addCriterion("house_ts not between", value1, value2, "houseTs");
            return (Criteria) this;
        }

        public Criteria andCarstatusIsNull() {
            addCriterion("carstatus is null");
            return (Criteria) this;
        }

        public Criteria andCarstatusIsNotNull() {
            addCriterion("carstatus is not null");
            return (Criteria) this;
        }

        public Criteria andCarstatusEqualTo(String value) {
            addCriterion("carstatus =", value, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusNotEqualTo(String value) {
            addCriterion("carstatus <>", value, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusGreaterThan(String value) {
            addCriterion("carstatus >", value, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusGreaterThanOrEqualTo(String value) {
            addCriterion("carstatus >=", value, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusLessThan(String value) {
            addCriterion("carstatus <", value, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusLessThanOrEqualTo(String value) {
            addCriterion("carstatus <=", value, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusLike(String value) {
            addCriterion("carstatus like", value, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusNotLike(String value) {
            addCriterion("carstatus not like", value, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusIn(List<String> values) {
            addCriterion("carstatus in", values, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusNotIn(List<String> values) {
            addCriterion("carstatus not in", values, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusBetween(String value1, String value2) {
            addCriterion("carstatus between", value1, value2, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCarstatusNotBetween(String value1, String value2) {
            addCriterion("carstatus not between", value1, value2, "carstatus");
            return (Criteria) this;
        }

        public Criteria andCartypeIsNull() {
            addCriterion("cartype is null");
            return (Criteria) this;
        }

        public Criteria andCartypeIsNotNull() {
            addCriterion("cartype is not null");
            return (Criteria) this;
        }

        public Criteria andCartypeEqualTo(String value) {
            addCriterion("cartype =", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeNotEqualTo(String value) {
            addCriterion("cartype <>", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeGreaterThan(String value) {
            addCriterion("cartype >", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeGreaterThanOrEqualTo(String value) {
            addCriterion("cartype >=", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeLessThan(String value) {
            addCriterion("cartype <", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeLessThanOrEqualTo(String value) {
            addCriterion("cartype <=", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeLike(String value) {
            addCriterion("cartype like", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeNotLike(String value) {
            addCriterion("cartype not like", value, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeIn(List<String> values) {
            addCriterion("cartype in", values, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeNotIn(List<String> values) {
            addCriterion("cartype not in", values, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeBetween(String value1, String value2) {
            addCriterion("cartype between", value1, value2, "cartype");
            return (Criteria) this;
        }

        public Criteria andCartypeNotBetween(String value1, String value2) {
            addCriterion("cartype not between", value1, value2, "cartype");
            return (Criteria) this;
        }

        public Criteria andCarinfoIsNull() {
            addCriterion("carinfo is null");
            return (Criteria) this;
        }

        public Criteria andCarinfoIsNotNull() {
            addCriterion("carinfo is not null");
            return (Criteria) this;
        }

        public Criteria andCarinfoEqualTo(String value) {
            addCriterion("carinfo =", value, "carinfo");
            return (Criteria) this;
        }

        public Criteria andCarinfoNotEqualTo(String value) {
            addCriterion("carinfo <>", value, "carinfo");
            return (Criteria) this;
        }

        public Criteria andCarinfoGreaterThan(String value) {
            addCriterion("carinfo >", value, "carinfo");
            return (Criteria) this;
        }

        public Criteria andCarinfoGreaterThanOrEqualTo(String value) {
            addCriterion("carinfo >=", value, "carinfo");
            return (Criteria) this;
        }

        public Criteria andCarinfoLessThan(String value) {
            addCriterion("carinfo <", value, "carinfo");
            return (Criteria) this;
        }

        public Criteria andCarinfoLessThanOrEqualTo(String value) {
            addCriterion("carinfo <=", value, "carinfo");
            return (Criteria) this;
        }

        public Criteria andCarinfoLike(String value) {
            addCriterion("carinfo like", value, "carinfo");
            return (Criteria) this;
        }

        public Criteria andCarinfoNotLike(String value) {
            addCriterion("carinfo not like", value, "carinfo");
            return (Criteria) this;
        }

        public Criteria andCarinfoIn(List<String> values) {
            addCriterion("carinfo in", values, "carinfo");
            return (Criteria) this;
        }

        public Criteria andCarinfoNotIn(List<String> values) {
            addCriterion("carinfo not in", values, "carinfo");
            return (Criteria) this;
        }

        public Criteria andCarinfoBetween(String value1, String value2) {
            addCriterion("carinfo between", value1, value2, "carinfo");
            return (Criteria) this;
        }

        public Criteria andCarinfoNotBetween(String value1, String value2) {
            addCriterion("carinfo not between", value1, value2, "carinfo");
            return (Criteria) this;
        }

        public Criteria andCarurlIsNull() {
            addCriterion("carurl is null");
            return (Criteria) this;
        }

        public Criteria andCarurlIsNotNull() {
            addCriterion("carurl is not null");
            return (Criteria) this;
        }

        public Criteria andCarurlEqualTo(String value) {
            addCriterion("carurl =", value, "carurl");
            return (Criteria) this;
        }

        public Criteria andCarurlNotEqualTo(String value) {
            addCriterion("carurl <>", value, "carurl");
            return (Criteria) this;
        }

        public Criteria andCarurlGreaterThan(String value) {
            addCriterion("carurl >", value, "carurl");
            return (Criteria) this;
        }

        public Criteria andCarurlGreaterThanOrEqualTo(String value) {
            addCriterion("carurl >=", value, "carurl");
            return (Criteria) this;
        }

        public Criteria andCarurlLessThan(String value) {
            addCriterion("carurl <", value, "carurl");
            return (Criteria) this;
        }

        public Criteria andCarurlLessThanOrEqualTo(String value) {
            addCriterion("carurl <=", value, "carurl");
            return (Criteria) this;
        }

        public Criteria andCarurlLike(String value) {
            addCriterion("carurl like", value, "carurl");
            return (Criteria) this;
        }

        public Criteria andCarurlNotLike(String value) {
            addCriterion("carurl not like", value, "carurl");
            return (Criteria) this;
        }

        public Criteria andCarurlIn(List<String> values) {
            addCriterion("carurl in", values, "carurl");
            return (Criteria) this;
        }

        public Criteria andCarurlNotIn(List<String> values) {
            addCriterion("carurl not in", values, "carurl");
            return (Criteria) this;
        }

        public Criteria andCarurlBetween(String value1, String value2) {
            addCriterion("carurl between", value1, value2, "carurl");
            return (Criteria) this;
        }

        public Criteria andCarurlNotBetween(String value1, String value2) {
            addCriterion("carurl not between", value1, value2, "carurl");
            return (Criteria) this;
        }

        public Criteria andCarTsIsNull() {
            addCriterion("car_ts is null");
            return (Criteria) this;
        }

        public Criteria andCarTsIsNotNull() {
            addCriterion("car_ts is not null");
            return (Criteria) this;
        }

        public Criteria andCarTsEqualTo(Date value) {
            addCriterion("car_ts =", value, "carTs");
            return (Criteria) this;
        }

        public Criteria andCarTsNotEqualTo(Date value) {
            addCriterion("car_ts <>", value, "carTs");
            return (Criteria) this;
        }

        public Criteria andCarTsGreaterThan(Date value) {
            addCriterion("car_ts >", value, "carTs");
            return (Criteria) this;
        }

        public Criteria andCarTsGreaterThanOrEqualTo(Date value) {
            addCriterion("car_ts >=", value, "carTs");
            return (Criteria) this;
        }

        public Criteria andCarTsLessThan(Date value) {
            addCriterion("car_ts <", value, "carTs");
            return (Criteria) this;
        }

        public Criteria andCarTsLessThanOrEqualTo(Date value) {
            addCriterion("car_ts <=", value, "carTs");
            return (Criteria) this;
        }

        public Criteria andCarTsIn(List<Date> values) {
            addCriterion("car_ts in", values, "carTs");
            return (Criteria) this;
        }

        public Criteria andCarTsNotIn(List<Date> values) {
            addCriterion("car_ts not in", values, "carTs");
            return (Criteria) this;
        }

        public Criteria andCarTsBetween(Date value1, Date value2) {
            addCriterion("car_ts between", value1, value2, "carTs");
            return (Criteria) this;
        }

        public Criteria andCarTsNotBetween(Date value1, Date value2) {
            addCriterion("car_ts not between", value1, value2, "carTs");
            return (Criteria) this;
        }

        public Criteria andDegreestatusIsNull() {
            addCriterion("degreestatus is null");
            return (Criteria) this;
        }

        public Criteria andDegreestatusIsNotNull() {
            addCriterion("degreestatus is not null");
            return (Criteria) this;
        }

        public Criteria andDegreestatusEqualTo(String value) {
            addCriterion("degreestatus =", value, "degreestatus");
            return (Criteria) this;
        }

        public Criteria andDegreestatusNotEqualTo(String value) {
            addCriterion("degreestatus <>", value, "degreestatus");
            return (Criteria) this;
        }

        public Criteria andDegreestatusGreaterThan(String value) {
            addCriterion("degreestatus >", value, "degreestatus");
            return (Criteria) this;
        }

        public Criteria andDegreestatusGreaterThanOrEqualTo(String value) {
            addCriterion("degreestatus >=", value, "degreestatus");
            return (Criteria) this;
        }

        public Criteria andDegreestatusLessThan(String value) {
            addCriterion("degreestatus <", value, "degreestatus");
            return (Criteria) this;
        }

        public Criteria andDegreestatusLessThanOrEqualTo(String value) {
            addCriterion("degreestatus <=", value, "degreestatus");
            return (Criteria) this;
        }

        public Criteria andDegreestatusLike(String value) {
            addCriterion("degreestatus like", value, "degreestatus");
            return (Criteria) this;
        }

        public Criteria andDegreestatusNotLike(String value) {
            addCriterion("degreestatus not like", value, "degreestatus");
            return (Criteria) this;
        }

        public Criteria andDegreestatusIn(List<String> values) {
            addCriterion("degreestatus in", values, "degreestatus");
            return (Criteria) this;
        }

        public Criteria andDegreestatusNotIn(List<String> values) {
            addCriterion("degreestatus not in", values, "degreestatus");
            return (Criteria) this;
        }

        public Criteria andDegreestatusBetween(String value1, String value2) {
            addCriterion("degreestatus between", value1, value2, "degreestatus");
            return (Criteria) this;
        }

        public Criteria andDegreestatusNotBetween(String value1, String value2) {
            addCriterion("degreestatus not between", value1, value2, "degreestatus");
            return (Criteria) this;
        }

        public Criteria andDegreelevelIsNull() {
            addCriterion("degreelevel is null");
            return (Criteria) this;
        }

        public Criteria andDegreelevelIsNotNull() {
            addCriterion("degreelevel is not null");
            return (Criteria) this;
        }

        public Criteria andDegreelevelEqualTo(String value) {
            addCriterion("degreelevel =", value, "degreelevel");
            return (Criteria) this;
        }

        public Criteria andDegreelevelNotEqualTo(String value) {
            addCriterion("degreelevel <>", value, "degreelevel");
            return (Criteria) this;
        }

        public Criteria andDegreelevelGreaterThan(String value) {
            addCriterion("degreelevel >", value, "degreelevel");
            return (Criteria) this;
        }

        public Criteria andDegreelevelGreaterThanOrEqualTo(String value) {
            addCriterion("degreelevel >=", value, "degreelevel");
            return (Criteria) this;
        }

        public Criteria andDegreelevelLessThan(String value) {
            addCriterion("degreelevel <", value, "degreelevel");
            return (Criteria) this;
        }

        public Criteria andDegreelevelLessThanOrEqualTo(String value) {
            addCriterion("degreelevel <=", value, "degreelevel");
            return (Criteria) this;
        }

        public Criteria andDegreelevelLike(String value) {
            addCriterion("degreelevel like", value, "degreelevel");
            return (Criteria) this;
        }

        public Criteria andDegreelevelNotLike(String value) {
            addCriterion("degreelevel not like", value, "degreelevel");
            return (Criteria) this;
        }

        public Criteria andDegreelevelIn(List<String> values) {
            addCriterion("degreelevel in", values, "degreelevel");
            return (Criteria) this;
        }

        public Criteria andDegreelevelNotIn(List<String> values) {
            addCriterion("degreelevel not in", values, "degreelevel");
            return (Criteria) this;
        }

        public Criteria andDegreelevelBetween(String value1, String value2) {
            addCriterion("degreelevel between", value1, value2, "degreelevel");
            return (Criteria) this;
        }

        public Criteria andDegreelevelNotBetween(String value1, String value2) {
            addCriterion("degreelevel not between", value1, value2, "degreelevel");
            return (Criteria) this;
        }

        public Criteria andDegreeurlIsNull() {
            addCriterion("degreeurl is null");
            return (Criteria) this;
        }

        public Criteria andDegreeurlIsNotNull() {
            addCriterion("degreeurl is not null");
            return (Criteria) this;
        }

        public Criteria andDegreeurlEqualTo(String value) {
            addCriterion("degreeurl =", value, "degreeurl");
            return (Criteria) this;
        }

        public Criteria andDegreeurlNotEqualTo(String value) {
            addCriterion("degreeurl <>", value, "degreeurl");
            return (Criteria) this;
        }

        public Criteria andDegreeurlGreaterThan(String value) {
            addCriterion("degreeurl >", value, "degreeurl");
            return (Criteria) this;
        }

        public Criteria andDegreeurlGreaterThanOrEqualTo(String value) {
            addCriterion("degreeurl >=", value, "degreeurl");
            return (Criteria) this;
        }

        public Criteria andDegreeurlLessThan(String value) {
            addCriterion("degreeurl <", value, "degreeurl");
            return (Criteria) this;
        }

        public Criteria andDegreeurlLessThanOrEqualTo(String value) {
            addCriterion("degreeurl <=", value, "degreeurl");
            return (Criteria) this;
        }

        public Criteria andDegreeurlLike(String value) {
            addCriterion("degreeurl like", value, "degreeurl");
            return (Criteria) this;
        }

        public Criteria andDegreeurlNotLike(String value) {
            addCriterion("degreeurl not like", value, "degreeurl");
            return (Criteria) this;
        }

        public Criteria andDegreeurlIn(List<String> values) {
            addCriterion("degreeurl in", values, "degreeurl");
            return (Criteria) this;
        }

        public Criteria andDegreeurlNotIn(List<String> values) {
            addCriterion("degreeurl not in", values, "degreeurl");
            return (Criteria) this;
        }

        public Criteria andDegreeurlBetween(String value1, String value2) {
            addCriterion("degreeurl between", value1, value2, "degreeurl");
            return (Criteria) this;
        }

        public Criteria andDegreeurlNotBetween(String value1, String value2) {
            addCriterion("degreeurl not between", value1, value2, "degreeurl");
            return (Criteria) this;
        }

        public Criteria andDegreeTsIsNull() {
            addCriterion("degree_ts is null");
            return (Criteria) this;
        }

        public Criteria andDegreeTsIsNotNull() {
            addCriterion("degree_ts is not null");
            return (Criteria) this;
        }

        public Criteria andDegreeTsEqualTo(String value) {
            addCriterion("degree_ts =", value, "degreeTs");
            return (Criteria) this;
        }

        public Criteria andDegreeTsNotEqualTo(String value) {
            addCriterion("degree_ts <>", value, "degreeTs");
            return (Criteria) this;
        }

        public Criteria andDegreeTsGreaterThan(String value) {
            addCriterion("degree_ts >", value, "degreeTs");
            return (Criteria) this;
        }

        public Criteria andDegreeTsGreaterThanOrEqualTo(String value) {
            addCriterion("degree_ts >=", value, "degreeTs");
            return (Criteria) this;
        }

        public Criteria andDegreeTsLessThan(String value) {
            addCriterion("degree_ts <", value, "degreeTs");
            return (Criteria) this;
        }

        public Criteria andDegreeTsLessThanOrEqualTo(String value) {
            addCriterion("degree_ts <=", value, "degreeTs");
            return (Criteria) this;
        }

        public Criteria andDegreeTsLike(String value) {
            addCriterion("degree_ts like", value, "degreeTs");
            return (Criteria) this;
        }

        public Criteria andDegreeTsNotLike(String value) {
            addCriterion("degree_ts not like", value, "degreeTs");
            return (Criteria) this;
        }

        public Criteria andDegreeTsIn(List<String> values) {
            addCriterion("degree_ts in", values, "degreeTs");
            return (Criteria) this;
        }

        public Criteria andDegreeTsNotIn(List<String> values) {
            addCriterion("degree_ts not in", values, "degreeTs");
            return (Criteria) this;
        }

        public Criteria andDegreeTsBetween(String value1, String value2) {
            addCriterion("degree_ts between", value1, value2, "degreeTs");
            return (Criteria) this;
        }

        public Criteria andDegreeTsNotBetween(String value1, String value2) {
            addCriterion("degree_ts not between", value1, value2, "degreeTs");
            return (Criteria) this;
        }

        public Criteria andHeadurlIsNull() {
            addCriterion("headurl is null");
            return (Criteria) this;
        }

        public Criteria andHeadurlIsNotNull() {
            addCriterion("headurl is not null");
            return (Criteria) this;
        }

        public Criteria andHeadurlEqualTo(String value) {
            addCriterion("headurl =", value, "headurl");
            return (Criteria) this;
        }

        public Criteria andHeadurlNotEqualTo(String value) {
            addCriterion("headurl <>", value, "headurl");
            return (Criteria) this;
        }

        public Criteria andHeadurlGreaterThan(String value) {
            addCriterion("headurl >", value, "headurl");
            return (Criteria) this;
        }

        public Criteria andHeadurlGreaterThanOrEqualTo(String value) {
            addCriterion("headurl >=", value, "headurl");
            return (Criteria) this;
        }

        public Criteria andHeadurlLessThan(String value) {
            addCriterion("headurl <", value, "headurl");
            return (Criteria) this;
        }

        public Criteria andHeadurlLessThanOrEqualTo(String value) {
            addCriterion("headurl <=", value, "headurl");
            return (Criteria) this;
        }

        public Criteria andHeadurlLike(String value) {
            addCriterion("headurl like", value, "headurl");
            return (Criteria) this;
        }

        public Criteria andHeadurlNotLike(String value) {
            addCriterion("headurl not like", value, "headurl");
            return (Criteria) this;
        }

        public Criteria andHeadurlIn(List<String> values) {
            addCriterion("headurl in", values, "headurl");
            return (Criteria) this;
        }

        public Criteria andHeadurlNotIn(List<String> values) {
            addCriterion("headurl not in", values, "headurl");
            return (Criteria) this;
        }

        public Criteria andHeadurlBetween(String value1, String value2) {
            addCriterion("headurl between", value1, value2, "headurl");
            return (Criteria) this;
        }

        public Criteria andHeadurlNotBetween(String value1, String value2) {
            addCriterion("headurl not between", value1, value2, "headurl");
            return (Criteria) this;
        }

        public Criteria andHeadTsIsNull() {
            addCriterion("head_ts is null");
            return (Criteria) this;
        }

        public Criteria andHeadTsIsNotNull() {
            addCriterion("head_ts is not null");
            return (Criteria) this;
        }

        public Criteria andHeadTsEqualTo(Date value) {
            addCriterion("head_ts =", value, "headTs");
            return (Criteria) this;
        }

        public Criteria andHeadTsNotEqualTo(Date value) {
            addCriterion("head_ts <>", value, "headTs");
            return (Criteria) this;
        }

        public Criteria andHeadTsGreaterThan(Date value) {
            addCriterion("head_ts >", value, "headTs");
            return (Criteria) this;
        }

        public Criteria andHeadTsGreaterThanOrEqualTo(Date value) {
            addCriterion("head_ts >=", value, "headTs");
            return (Criteria) this;
        }

        public Criteria andHeadTsLessThan(Date value) {
            addCriterion("head_ts <", value, "headTs");
            return (Criteria) this;
        }

        public Criteria andHeadTsLessThanOrEqualTo(Date value) {
            addCriterion("head_ts <=", value, "headTs");
            return (Criteria) this;
        }

        public Criteria andHeadTsIn(List<Date> values) {
            addCriterion("head_ts in", values, "headTs");
            return (Criteria) this;
        }

        public Criteria andHeadTsNotIn(List<Date> values) {
            addCriterion("head_ts not in", values, "headTs");
            return (Criteria) this;
        }

        public Criteria andHeadTsBetween(Date value1, Date value2) {
            addCriterion("head_ts between", value1, value2, "headTs");
            return (Criteria) this;
        }

        public Criteria andHeadTsNotBetween(Date value1, Date value2) {
            addCriterion("head_ts not between", value1, value2, "headTs");
            return (Criteria) this;
        }

        public Criteria andIduserIsNull() {
            addCriterion("iduser is null");
            return (Criteria) this;
        }

        public Criteria andIduserIsNotNull() {
            addCriterion("iduser is not null");
            return (Criteria) this;
        }

        public Criteria andIduserEqualTo(String value) {
            addCriterion("iduser =", value, "iduser");
            return (Criteria) this;
        }

        public Criteria andIduserNotEqualTo(String value) {
            addCriterion("iduser <>", value, "iduser");
            return (Criteria) this;
        }

        public Criteria andIduserGreaterThan(String value) {
            addCriterion("iduser >", value, "iduser");
            return (Criteria) this;
        }

        public Criteria andIduserGreaterThanOrEqualTo(String value) {
            addCriterion("iduser >=", value, "iduser");
            return (Criteria) this;
        }

        public Criteria andIduserLessThan(String value) {
            addCriterion("iduser <", value, "iduser");
            return (Criteria) this;
        }

        public Criteria andIduserLessThanOrEqualTo(String value) {
            addCriterion("iduser <=", value, "iduser");
            return (Criteria) this;
        }

        public Criteria andIduserLike(String value) {
            addCriterion("iduser like", value, "iduser");
            return (Criteria) this;
        }

        public Criteria andIduserNotLike(String value) {
            addCriterion("iduser not like", value, "iduser");
            return (Criteria) this;
        }

        public Criteria andIduserIn(List<String> values) {
            addCriterion("iduser in", values, "iduser");
            return (Criteria) this;
        }

        public Criteria andIduserNotIn(List<String> values) {
            addCriterion("iduser not in", values, "iduser");
            return (Criteria) this;
        }

        public Criteria andIduserBetween(String value1, String value2) {
            addCriterion("iduser between", value1, value2, "iduser");
            return (Criteria) this;
        }

        public Criteria andIduserNotBetween(String value1, String value2) {
            addCriterion("iduser not between", value1, value2, "iduser");
            return (Criteria) this;
        }

        public Criteria andIduserinfoIsNull() {
            addCriterion("iduserinfo is null");
            return (Criteria) this;
        }

        public Criteria andIduserinfoIsNotNull() {
            addCriterion("iduserinfo is not null");
            return (Criteria) this;
        }

        public Criteria andIduserinfoEqualTo(String value) {
            addCriterion("iduserinfo =", value, "iduserinfo");
            return (Criteria) this;
        }

        public Criteria andIduserinfoNotEqualTo(String value) {
            addCriterion("iduserinfo <>", value, "iduserinfo");
            return (Criteria) this;
        }

        public Criteria andIduserinfoGreaterThan(String value) {
            addCriterion("iduserinfo >", value, "iduserinfo");
            return (Criteria) this;
        }

        public Criteria andIduserinfoGreaterThanOrEqualTo(String value) {
            addCriterion("iduserinfo >=", value, "iduserinfo");
            return (Criteria) this;
        }

        public Criteria andIduserinfoLessThan(String value) {
            addCriterion("iduserinfo <", value, "iduserinfo");
            return (Criteria) this;
        }

        public Criteria andIduserinfoLessThanOrEqualTo(String value) {
            addCriterion("iduserinfo <=", value, "iduserinfo");
            return (Criteria) this;
        }

        public Criteria andIduserinfoLike(String value) {
            addCriterion("iduserinfo like", value, "iduserinfo");
            return (Criteria) this;
        }

        public Criteria andIduserinfoNotLike(String value) {
            addCriterion("iduserinfo not like", value, "iduserinfo");
            return (Criteria) this;
        }

        public Criteria andIduserinfoIn(List<String> values) {
            addCriterion("iduserinfo in", values, "iduserinfo");
            return (Criteria) this;
        }

        public Criteria andIduserinfoNotIn(List<String> values) {
            addCriterion("iduserinfo not in", values, "iduserinfo");
            return (Criteria) this;
        }

        public Criteria andIduserinfoBetween(String value1, String value2) {
            addCriterion("iduserinfo between", value1, value2, "iduserinfo");
            return (Criteria) this;
        }

        public Criteria andIduserinfoNotBetween(String value1, String value2) {
            addCriterion("iduserinfo not between", value1, value2, "iduserinfo");
            return (Criteria) this;
        }

        public Criteria andAddtimeIsNull() {
            addCriterion("addtime is null");
            return (Criteria) this;
        }

        public Criteria andAddtimeIsNotNull() {
            addCriterion("addtime is not null");
            return (Criteria) this;
        }

        public Criteria andAddtimeEqualTo(Date value) {
            addCriterion("addtime =", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotEqualTo(Date value) {
            addCriterion("addtime <>", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeGreaterThan(Date value) {
            addCriterion("addtime >", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("addtime >=", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeLessThan(Date value) {
            addCriterion("addtime <", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeLessThanOrEqualTo(Date value) {
            addCriterion("addtime <=", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeIn(List<Date> values) {
            addCriterion("addtime in", values, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotIn(List<Date> values) {
            addCriterion("addtime not in", values, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeBetween(Date value1, Date value2) {
            addCriterion("addtime between", value1, value2, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotBetween(Date value1, Date value2) {
            addCriterion("addtime not between", value1, value2, "addtime");
            return (Criteria) this;
        }

        public Criteria andTsIsNull() {
            addCriterion("ts is null");
            return (Criteria) this;
        }

        public Criteria andTsIsNotNull() {
            addCriterion("ts is not null");
            return (Criteria) this;
        }

        public Criteria andTsEqualTo(Date value) {
            addCriterion("ts =", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotEqualTo(Date value) {
            addCriterion("ts <>", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsGreaterThan(Date value) {
            addCriterion("ts >", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsGreaterThanOrEqualTo(Date value) {
            addCriterion("ts >=", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsLessThan(Date value) {
            addCriterion("ts <", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsLessThanOrEqualTo(Date value) {
            addCriterion("ts <=", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsIn(List<Date> values) {
            addCriterion("ts in", values, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotIn(List<Date> values) {
            addCriterion("ts not in", values, "ts");
            return (Criteria) this;
        }

        public Criteria andTsBetween(Date value1, Date value2) {
            addCriterion("ts between", value1, value2, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotBetween(Date value1, Date value2) {
            addCriterion("ts not between", value1, value2, "ts");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userextrainfo
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userextrainfo
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}