package com.jakcray.springbootshiro.mybatisutils.dao;

import java.util.Date;

public class UserInfoDAO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.iduserinfo
     *
     * @mbggenerated
     */
    private String iduserinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.b_name
     *
     * @mbggenerated
     */
    private String bName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.b_birthday
     *
     * @mbggenerated
     */
    private Date bBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.b_constellation
     *
     * @mbggenerated
     */
    private String bConstellation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.b_height
     *
     * @mbggenerated
     */
    private String bHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.b_annualsalary
     *
     * @mbggenerated
     */
    private String bAnnualsalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.b_livecity
     *
     * @mbggenerated
     */
    private String bLivecity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.b_expect
     *
     * @mbggenerated
     */
    private String bExpect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.b_wechat
     *
     * @mbggenerated
     */
    private String bWechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.i_nation
     *
     * @mbggenerated
     */
    private String iNation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.i_hometown
     *
     * @mbggenerated
     */
    private String iHometown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.i_naritalstatus
     *
     * @mbggenerated
     */
    private String iNaritalstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.i_occupation
     *
     * @mbggenerated
     */
    private String iOccupation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.i_faith
     *
     * @mbggenerated
     */
    private String iFaith;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.i_drinkwine
     *
     * @mbggenerated
     */
    private String iDrinkwine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.i_smoking
     *
     * @mbggenerated
     */
    private String iSmoking;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.i_sortinhome
     *
     * @mbggenerated
     */
    private String iSortinhome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.i_hasson
     *
     * @mbggenerated
     */
    private String iHasson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.i_weight
     *
     * @mbggenerated
     */
    private String iWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.s_age
     *
     * @mbggenerated
     */
    private String sAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.s_height
     *
     * @mbggenerated
     */
    private String sHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.s_annualincome
     *
     * @mbggenerated
     */
    private String sAnnualincome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.s_hometown
     *
     * @mbggenerated
     */
    private String sHometown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.s_maritalstatus
     *
     * @mbggenerated
     */
    private String sMaritalstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.s_faith
     *
     * @mbggenerated
     */
    private String sFaith;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.s_drink
     *
     * @mbggenerated
     */
    private String sDrink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.s_smoking
     *
     * @mbggenerated
     */
    private String sSmoking;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.s_hasson
     *
     * @mbggenerated
     */
    private String sHasson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.s_weight
     *
     * @mbggenerated
     */
    private String sWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.s_constellation
     *
     * @mbggenerated
     */
    private String sConstellation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.p_moive
     *
     * @mbggenerated
     */
    private String pMoive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.p_music
     *
     * @mbggenerated
     */
    private String pMusic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.p_book
     *
     * @mbggenerated
     */
    private String pBook;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.p_food
     *
     * @mbggenerated
     */
    private String pFood;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.p_sport
     *
     * @mbggenerated
     */
    private String pSport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.iduserextrainfo
     *
     * @mbggenerated
     */
    private String iduserextrainfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.iduser
     *
     * @mbggenerated
     */
    private String iduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.ts
     *
     * @mbggenerated
     */
    private Date ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.iduserinfo
     *
     * @return the value of userinfo.iduserinfo
     *
     * @mbggenerated
     */
    public String getIduserinfo() {
        return iduserinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.iduserinfo
     *
     * @param iduserinfo the value for userinfo.iduserinfo
     *
     * @mbggenerated
     */
    public void setIduserinfo(String iduserinfo) {
        this.iduserinfo = iduserinfo == null ? null : iduserinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.b_name
     *
     * @return the value of userinfo.b_name
     *
     * @mbggenerated
     */
    public String getbName() {
        return bName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.b_name
     *
     * @param bName the value for userinfo.b_name
     *
     * @mbggenerated
     */
    public void setbName(String bName) {
        this.bName = bName == null ? null : bName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.b_birthday
     *
     * @return the value of userinfo.b_birthday
     *
     * @mbggenerated
     */
    public Date getbBirthday() {
        return bBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.b_birthday
     *
     * @param bBirthday the value for userinfo.b_birthday
     *
     * @mbggenerated
     */
    public void setbBirthday(Date bBirthday) {
        this.bBirthday = bBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.b_constellation
     *
     * @return the value of userinfo.b_constellation
     *
     * @mbggenerated
     */
    public String getbConstellation() {
        return bConstellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.b_constellation
     *
     * @param bConstellation the value for userinfo.b_constellation
     *
     * @mbggenerated
     */
    public void setbConstellation(String bConstellation) {
        this.bConstellation = bConstellation == null ? null : bConstellation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.b_height
     *
     * @return the value of userinfo.b_height
     *
     * @mbggenerated
     */
    public String getbHeight() {
        return bHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.b_height
     *
     * @param bHeight the value for userinfo.b_height
     *
     * @mbggenerated
     */
    public void setbHeight(String bHeight) {
        this.bHeight = bHeight == null ? null : bHeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.b_annualsalary
     *
     * @return the value of userinfo.b_annualsalary
     *
     * @mbggenerated
     */
    public String getbAnnualsalary() {
        return bAnnualsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.b_annualsalary
     *
     * @param bAnnualsalary the value for userinfo.b_annualsalary
     *
     * @mbggenerated
     */
    public void setbAnnualsalary(String bAnnualsalary) {
        this.bAnnualsalary = bAnnualsalary == null ? null : bAnnualsalary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.b_livecity
     *
     * @return the value of userinfo.b_livecity
     *
     * @mbggenerated
     */
    public String getbLivecity() {
        return bLivecity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.b_livecity
     *
     * @param bLivecity the value for userinfo.b_livecity
     *
     * @mbggenerated
     */
    public void setbLivecity(String bLivecity) {
        this.bLivecity = bLivecity == null ? null : bLivecity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.b_expect
     *
     * @return the value of userinfo.b_expect
     *
     * @mbggenerated
     */
    public String getbExpect() {
        return bExpect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.b_expect
     *
     * @param bExpect the value for userinfo.b_expect
     *
     * @mbggenerated
     */
    public void setbExpect(String bExpect) {
        this.bExpect = bExpect == null ? null : bExpect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.b_wechat
     *
     * @return the value of userinfo.b_wechat
     *
     * @mbggenerated
     */
    public String getbWechat() {
        return bWechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.b_wechat
     *
     * @param bWechat the value for userinfo.b_wechat
     *
     * @mbggenerated
     */
    public void setbWechat(String bWechat) {
        this.bWechat = bWechat == null ? null : bWechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.i_nation
     *
     * @return the value of userinfo.i_nation
     *
     * @mbggenerated
     */
    public String getiNation() {
        return iNation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.i_nation
     *
     * @param iNation the value for userinfo.i_nation
     *
     * @mbggenerated
     */
    public void setiNation(String iNation) {
        this.iNation = iNation == null ? null : iNation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.i_hometown
     *
     * @return the value of userinfo.i_hometown
     *
     * @mbggenerated
     */
    public String getiHometown() {
        return iHometown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.i_hometown
     *
     * @param iHometown the value for userinfo.i_hometown
     *
     * @mbggenerated
     */
    public void setiHometown(String iHometown) {
        this.iHometown = iHometown == null ? null : iHometown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.i_naritalstatus
     *
     * @return the value of userinfo.i_naritalstatus
     *
     * @mbggenerated
     */
    public String getiNaritalstatus() {
        return iNaritalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.i_naritalstatus
     *
     * @param iNaritalstatus the value for userinfo.i_naritalstatus
     *
     * @mbggenerated
     */
    public void setiNaritalstatus(String iNaritalstatus) {
        this.iNaritalstatus = iNaritalstatus == null ? null : iNaritalstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.i_occupation
     *
     * @return the value of userinfo.i_occupation
     *
     * @mbggenerated
     */
    public String getiOccupation() {
        return iOccupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.i_occupation
     *
     * @param iOccupation the value for userinfo.i_occupation
     *
     * @mbggenerated
     */
    public void setiOccupation(String iOccupation) {
        this.iOccupation = iOccupation == null ? null : iOccupation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.i_faith
     *
     * @return the value of userinfo.i_faith
     *
     * @mbggenerated
     */
    public String getiFaith() {
        return iFaith;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.i_faith
     *
     * @param iFaith the value for userinfo.i_faith
     *
     * @mbggenerated
     */
    public void setiFaith(String iFaith) {
        this.iFaith = iFaith == null ? null : iFaith.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.i_drinkwine
     *
     * @return the value of userinfo.i_drinkwine
     *
     * @mbggenerated
     */
    public String getiDrinkwine() {
        return iDrinkwine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.i_drinkwine
     *
     * @param iDrinkwine the value for userinfo.i_drinkwine
     *
     * @mbggenerated
     */
    public void setiDrinkwine(String iDrinkwine) {
        this.iDrinkwine = iDrinkwine == null ? null : iDrinkwine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.i_smoking
     *
     * @return the value of userinfo.i_smoking
     *
     * @mbggenerated
     */
    public String getiSmoking() {
        return iSmoking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.i_smoking
     *
     * @param iSmoking the value for userinfo.i_smoking
     *
     * @mbggenerated
     */
    public void setiSmoking(String iSmoking) {
        this.iSmoking = iSmoking == null ? null : iSmoking.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.i_sortinhome
     *
     * @return the value of userinfo.i_sortinhome
     *
     * @mbggenerated
     */
    public String getiSortinhome() {
        return iSortinhome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.i_sortinhome
     *
     * @param iSortinhome the value for userinfo.i_sortinhome
     *
     * @mbggenerated
     */
    public void setiSortinhome(String iSortinhome) {
        this.iSortinhome = iSortinhome == null ? null : iSortinhome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.i_hasson
     *
     * @return the value of userinfo.i_hasson
     *
     * @mbggenerated
     */
    public String getiHasson() {
        return iHasson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.i_hasson
     *
     * @param iHasson the value for userinfo.i_hasson
     *
     * @mbggenerated
     */
    public void setiHasson(String iHasson) {
        this.iHasson = iHasson == null ? null : iHasson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.i_weight
     *
     * @return the value of userinfo.i_weight
     *
     * @mbggenerated
     */
    public String getiWeight() {
        return iWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.i_weight
     *
     * @param iWeight the value for userinfo.i_weight
     *
     * @mbggenerated
     */
    public void setiWeight(String iWeight) {
        this.iWeight = iWeight == null ? null : iWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.s_age
     *
     * @return the value of userinfo.s_age
     *
     * @mbggenerated
     */
    public String getsAge() {
        return sAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.s_age
     *
     * @param sAge the value for userinfo.s_age
     *
     * @mbggenerated
     */
    public void setsAge(String sAge) {
        this.sAge = sAge == null ? null : sAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.s_height
     *
     * @return the value of userinfo.s_height
     *
     * @mbggenerated
     */
    public String getsHeight() {
        return sHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.s_height
     *
     * @param sHeight the value for userinfo.s_height
     *
     * @mbggenerated
     */
    public void setsHeight(String sHeight) {
        this.sHeight = sHeight == null ? null : sHeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.s_annualincome
     *
     * @return the value of userinfo.s_annualincome
     *
     * @mbggenerated
     */
    public String getsAnnualincome() {
        return sAnnualincome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.s_annualincome
     *
     * @param sAnnualincome the value for userinfo.s_annualincome
     *
     * @mbggenerated
     */
    public void setsAnnualincome(String sAnnualincome) {
        this.sAnnualincome = sAnnualincome == null ? null : sAnnualincome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.s_hometown
     *
     * @return the value of userinfo.s_hometown
     *
     * @mbggenerated
     */
    public String getsHometown() {
        return sHometown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.s_hometown
     *
     * @param sHometown the value for userinfo.s_hometown
     *
     * @mbggenerated
     */
    public void setsHometown(String sHometown) {
        this.sHometown = sHometown == null ? null : sHometown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.s_maritalstatus
     *
     * @return the value of userinfo.s_maritalstatus
     *
     * @mbggenerated
     */
    public String getsMaritalstatus() {
        return sMaritalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.s_maritalstatus
     *
     * @param sMaritalstatus the value for userinfo.s_maritalstatus
     *
     * @mbggenerated
     */
    public void setsMaritalstatus(String sMaritalstatus) {
        this.sMaritalstatus = sMaritalstatus == null ? null : sMaritalstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.s_faith
     *
     * @return the value of userinfo.s_faith
     *
     * @mbggenerated
     */
    public String getsFaith() {
        return sFaith;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.s_faith
     *
     * @param sFaith the value for userinfo.s_faith
     *
     * @mbggenerated
     */
    public void setsFaith(String sFaith) {
        this.sFaith = sFaith == null ? null : sFaith.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.s_drink
     *
     * @return the value of userinfo.s_drink
     *
     * @mbggenerated
     */
    public String getsDrink() {
        return sDrink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.s_drink
     *
     * @param sDrink the value for userinfo.s_drink
     *
     * @mbggenerated
     */
    public void setsDrink(String sDrink) {
        this.sDrink = sDrink == null ? null : sDrink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.s_smoking
     *
     * @return the value of userinfo.s_smoking
     *
     * @mbggenerated
     */
    public String getsSmoking() {
        return sSmoking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.s_smoking
     *
     * @param sSmoking the value for userinfo.s_smoking
     *
     * @mbggenerated
     */
    public void setsSmoking(String sSmoking) {
        this.sSmoking = sSmoking == null ? null : sSmoking.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.s_hasson
     *
     * @return the value of userinfo.s_hasson
     *
     * @mbggenerated
     */
    public String getsHasson() {
        return sHasson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.s_hasson
     *
     * @param sHasson the value for userinfo.s_hasson
     *
     * @mbggenerated
     */
    public void setsHasson(String sHasson) {
        this.sHasson = sHasson == null ? null : sHasson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.s_weight
     *
     * @return the value of userinfo.s_weight
     *
     * @mbggenerated
     */
    public String getsWeight() {
        return sWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.s_weight
     *
     * @param sWeight the value for userinfo.s_weight
     *
     * @mbggenerated
     */
    public void setsWeight(String sWeight) {
        this.sWeight = sWeight == null ? null : sWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.s_constellation
     *
     * @return the value of userinfo.s_constellation
     *
     * @mbggenerated
     */
    public String getsConstellation() {
        return sConstellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.s_constellation
     *
     * @param sConstellation the value for userinfo.s_constellation
     *
     * @mbggenerated
     */
    public void setsConstellation(String sConstellation) {
        this.sConstellation = sConstellation == null ? null : sConstellation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.p_moive
     *
     * @return the value of userinfo.p_moive
     *
     * @mbggenerated
     */
    public String getpMoive() {
        return pMoive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.p_moive
     *
     * @param pMoive the value for userinfo.p_moive
     *
     * @mbggenerated
     */
    public void setpMoive(String pMoive) {
        this.pMoive = pMoive == null ? null : pMoive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.p_music
     *
     * @return the value of userinfo.p_music
     *
     * @mbggenerated
     */
    public String getpMusic() {
        return pMusic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.p_music
     *
     * @param pMusic the value for userinfo.p_music
     *
     * @mbggenerated
     */
    public void setpMusic(String pMusic) {
        this.pMusic = pMusic == null ? null : pMusic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.p_book
     *
     * @return the value of userinfo.p_book
     *
     * @mbggenerated
     */
    public String getpBook() {
        return pBook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.p_book
     *
     * @param pBook the value for userinfo.p_book
     *
     * @mbggenerated
     */
    public void setpBook(String pBook) {
        this.pBook = pBook == null ? null : pBook.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.p_food
     *
     * @return the value of userinfo.p_food
     *
     * @mbggenerated
     */
    public String getpFood() {
        return pFood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.p_food
     *
     * @param pFood the value for userinfo.p_food
     *
     * @mbggenerated
     */
    public void setpFood(String pFood) {
        this.pFood = pFood == null ? null : pFood.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.p_sport
     *
     * @return the value of userinfo.p_sport
     *
     * @mbggenerated
     */
    public String getpSport() {
        return pSport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.p_sport
     *
     * @param pSport the value for userinfo.p_sport
     *
     * @mbggenerated
     */
    public void setpSport(String pSport) {
        this.pSport = pSport == null ? null : pSport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.iduserextrainfo
     *
     * @return the value of userinfo.iduserextrainfo
     *
     * @mbggenerated
     */
    public String getIduserextrainfo() {
        return iduserextrainfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.iduserextrainfo
     *
     * @param iduserextrainfo the value for userinfo.iduserextrainfo
     *
     * @mbggenerated
     */
    public void setIduserextrainfo(String iduserextrainfo) {
        this.iduserextrainfo = iduserextrainfo == null ? null : iduserextrainfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.iduser
     *
     * @return the value of userinfo.iduser
     *
     * @mbggenerated
     */
    public String getIduser() {
        return iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.iduser
     *
     * @param iduser the value for userinfo.iduser
     *
     * @mbggenerated
     */
    public void setIduser(String iduser) {
        this.iduser = iduser == null ? null : iduser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.addtime
     *
     * @return the value of userinfo.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.addtime
     *
     * @param addtime the value for userinfo.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.ts
     *
     * @return the value of userinfo.ts
     *
     * @mbggenerated
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.ts
     *
     * @param ts the value for userinfo.ts
     *
     * @mbggenerated
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }
}