package com.jakcray.springbootshiro.mybatisutils.dao;

import java.util.Date;

public class UserRoleDAO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.iduser_role
     *
     * @mbggenerated
     */
    private String iduserRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.iduser
     *
     * @mbggenerated
     */
    private String iduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.idrole
     *
     * @mbggenerated
     */
    private String idrole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.ts
     *
     * @mbggenerated
     */
    private Date ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.iduser_role
     *
     * @return the value of user_role.iduser_role
     *
     * @mbggenerated
     */
    public String getIduserRole() {
        return iduserRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.iduser_role
     *
     * @param iduserRole the value for user_role.iduser_role
     *
     * @mbggenerated
     */
    public void setIduserRole(String iduserRole) {
        this.iduserRole = iduserRole == null ? null : iduserRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.iduser
     *
     * @return the value of user_role.iduser
     *
     * @mbggenerated
     */
    public String getIduser() {
        return iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.iduser
     *
     * @param iduser the value for user_role.iduser
     *
     * @mbggenerated
     */
    public void setIduser(String iduser) {
        this.iduser = iduser == null ? null : iduser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.idrole
     *
     * @return the value of user_role.idrole
     *
     * @mbggenerated
     */
    public String getIdrole() {
        return idrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.idrole
     *
     * @param idrole the value for user_role.idrole
     *
     * @mbggenerated
     */
    public void setIdrole(String idrole) {
        this.idrole = idrole == null ? null : idrole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.addtime
     *
     * @return the value of user_role.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.addtime
     *
     * @param addtime the value for user_role.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.ts
     *
     * @return the value of user_role.ts
     *
     * @mbggenerated
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.ts
     *
     * @param ts the value for user_role.ts
     *
     * @mbggenerated
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }
}